-- 사원 번호와 사원명과 부서명과 부서의 위치를 출력하는 뷰(VIEW_LOC)를 작성하라
CREATE VIEW VIEW_LOC
AS
SELECT EMPLOYEE_ID, FIRST_NAME ||' '||LAST_NAME AS NAME, E.DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT * FROM VIEW_LOC;
DROP VIEW VIEW_LOC;
-- 30번 부서 소속 사원의 이름과 입사일과 부서명을 출력하는 뷰(VIEW_DEPT30)를 작성하라
CREATE VIEW VIEW_DEPT30
AS
SELECT FIRST_NAME, HIRE_DATE, E.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.DEPARTMENT_ID = 30;

SELECT * FROM  VIEW_DEPT30;

-- 부서별 최대 급여 정보를 가지는 뷰(VIEW_DEPT_MAXSAL)를 생성하라
CREATE VIEW VIEW_DEPT_MAXSAL
AS
SELECT DEPARTMENT_ID, MAX(SALARY)AS MAXSAL FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

SELECT * FROM VIEW_DEPT_MAXSAL;

-- 급여를 많이 받는 순서대로 3명만 출력하는 뷰(VIEW_SAL_TOP3)와 인라인 뷰로 작성하라
CREATE VIEW VIEW_SAL_TOP3
AS
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;

SELECT * FROM VIEW_SAL_TOP3;
SELECT ROWNUM, EMPLOYEE_ID, FIRST_NAME, SALARY FROM VIEW_SAL_TOP3 WHERE ROWNUM <= 3;

SELECT ROWNUM, EMPLOYEE_ID, FIRST_NAME, SALARY
FROM (SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM <= 3;