-- TRIGGER 테스팅
-- EMP01 생성하고 트리거를 생성한다(입력이 될때마다 입력값을 출력해주는 트리거를 만든다)
DROP TABLE EMP01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(20),
    JOB VARCHAR2(50)
);
DESC EMP01;

CREATE OR REPLACE TRIGGER EMP01_TRIGGER
    AFTER INSERT ON EMP01
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE(:NEW.EMPNO || ',' || :NEW.ENAME || '신입사원이 입사했습니다.');
END;
/

INSERT INTO EMP01 VALUES((SELECT NVL(MAX(EMPNO),0)+1 FROM EMP01), DBMS_RANDOM.STRING('U',4), 'IT_DEV');


CREATE TABLE SAL01(
    SALNO NUMBER(4),
    SALARY NUMBER,
    EMPNO NUMBER(4)
);
ALTER TABLE SAL01 ADD CONSTRAINT SAL01_SALNO_PK PRIMARY KEY(SALNO);
ALTER TABLE SAL01 ADD CONSTRAINT SAL01_EMPNO_FK FOREIGN KEY(EMPNO) REFERENCES EMP01(EMPNO);

SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'SAL01';

CREATE SEQUENCE SAL01_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000
NOCYCLE
CACHE 2;

CREATE OR REPLACE TRIGGER EMP01_TRIGGER2
AFTER INSERT ON EMP01
FOR EACH ROW
BEGIN
    INSERT INTO SAL01 VALUES(SAL01_SEQ.NEXTVAL, 100000, :NEW.EMPNO);
    DBMS_OUTPUT.PUT_LINE(:NEW.EMPNO || '번호 사원이 SAL01 잘 들어왔습니다.');
END;
/

INSERT INTO EMP01 VALUES((SELECT NVL(MAX(EMPNO),0)+1 FROM EMP01), DBMS_RANDOM.STRING('U',4), 'IT_DEV');
SELECT * FROM EMP01;
SELECT * FROM SAL01;


-- EMP01 에서 사원의 정보를 제거했을때 SAL01 해당되는 사원의 정보가 삭제되도록 프로그램하시오.
CREATE OR REPLACE TRIGGER EMP01_TRIGGER3
    AFTER DELETE ON EMP01
    FOR EACH ROW
BEGIN
    -- SAL01 해당되는 사원의 정보가 삭제
    DELETE FROM SAL01 WHERE EMPNO = :OLD.EMPNO;
    DBMS_OUTPUT.PUT_LINE(:OLD.EMPNO || '번호가 SAL01에서 삭제되었습니다.');
END;
/

DELETE FROM EMP01 WHERE EMPNO = 4;
SELECT * FROM EMP01;
SELECT * FROM SAL01;

-- 상품테이블
CREATE TABLE PRODUCT(
    PCODE CHAR(6),
    PNAME VARCHAR2(12) NOT NULL,
    PCOMPANY VARCHAR2(12),
    PPRICE NUMBER(8),
    STOCK NUMBER DEFAULT 0
);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PCODE_PK PRIMARY KEY(PCODE);
DESC PRODUCT;

INSERT INTO PRODUCT(PCODE, PNAME, PCOMPANY, PPRICE)
VALUES('A00001','세탁기','LG',1500000);
INSERT INTO PRODUCT(PCODE, PNAME, PCOMPANY, PPRICE)
VALUES('A00002','컴퓨터','LG',1000000);
INSERT INTO PRODUCT(PCODE, PNAME, PCOMPANY, PPRICE)
VALUES('A00003','냉장고','삼성',4500000);

SELECT * FROM PRODUCT;

-- 입고테이블
CREATE TABLE RECEIVING(
    RNO NUMBER(6),
    PCODE CHAR(6),
    RDATE DATE DEFAULT SYSDATE,
    RQTY NUMBER(6),
    RPRICE NUMBER(8),
    RAMOUNT NUMBER(8)
);
ALTER TABLE RECEIVING ADD CONSTRAINT RECEIVING_RNO_PK PRIMARY KEY(RNO);
ALTER TABLE RECEIVING ADD CONSTRAINT RECEIVING_PCODE_FK FOREIGN KEY(PCODE) REFERENCES PRODUCT(PCODE);

DESC RECEIVING;

-- 트리거 생성 입고(RECEIVING) 입력이 되면 재고(PRODUCT) 수량의 입고 수량이 저장되는 트리거를 생성
CREATE OR REPLACE TRIGGER RECEIVING_TRIGGER01
    AFTER INSERT ON RECEIVING
    FOR EACH ROW
BEGIN
    UPDATE PRODUCT SET STOCK = STOCK + :NEW.RQTY WHERE PCODE = :NEW.PCODE;
END;
/

-- 입고수량 등록
INSERT INTO RECEIVING(RNO, PCODE, RQTY, RPRICE, RAMOUNT)
VALUES( (SELECT NVL(MAX(RNO),0)+1 FROM RECEIVING), 'A00002', 10, 680000, 780000);

INSERT INTO RECEIVING(RNO, PCODE, RQTY, RPRICE, RAMOUNT)
VALUES( (SELECT NVL(MAX(RNO),0)+1 FROM RECEIVING), 'A00003', 20, 3000000, 3000000);

INSERT INTO RECEIVING(RNO, PCODE, RQTY, RPRICE, RAMOUNT)
VALUES( (SELECT NVL(MAX(RNO),0)+1 FROM RECEIVING), 'A00001', 30, 1000000, 1000000);

INSERT INTO RECEIVING(RNO, PCODE, RQTY, RPRICE, RAMOUNT)
VALUES( (SELECT NVL(MAX(RNO),0)+1 FROM RECEIVING), 'A00001', 10, 1000000, 1000000);

SELECT * FROM PRODUCT;
SELECT * FROM RECEIVING;

-- 갱신트리거 만들기 입고수량을 30 => 10 진행을 했는데 마지막 10개를 5개 수정하면, PRODUCT 재고수량을 수정하는
-- 트리거를 만들것
CREATE OR REPLACE TRIGGER RECEIVING_TRIGGER
    AFTER UPDATE ON RECEIVING
    FOR EACH ROW
BEGIN
    UPDATE PRODUCT SET STOCK = STOCK + (-:OLD.RQTY + :NEW.RQTY) WHERE PCODE = :NEW.PCODE;
END;
/

UPDATE RECEIVING SET RQTY = 8, RPRICE = 1000000, RAMOUNT = 1000000 WHERE RNO = 3;
UPDATE RECEIVING SET RQTY = 4, RPRICE = 1000000, RAMOUNT = 1000000 WHERE RNO = 3;

SELECT * FROM PRODUCT;
SELECT * FROM RECEIVING;
DELETE FROM RECEIVING WHERE RNO = 4;

-- 삭제트리거(입고부분에서 삭제가 되면 재고부분에서 삭제된 수량을 빼준다)
CREATE OR REPLACE TRIGGER RECEIVING_DEL_TRIGGER
    AFTER DELETE ON RECEIVING
    FOR EACH ROW
BEGIN
    UPDATE PRODUCT SET STOCK = STOCK - (:OLD.RQTY) WHERE PCODE = :OLD.PCODE;
END;
/

SELECT * FROM RECEIVING;
SELECT * FROM PRODUCT;

DELETE FROM RECEIVING WHERE NO = 3;

