-- 문제 1 EMPLOYEES 테이블에 등록된 총사원의 수와 급여의 합, 급여의 평균을 변수에 대입하여 출력하여 보자.
DECLARE
    -- 변수선언
    TOTAL_EMPLOYEE NUMBER;
    TOTAL_SALARY NUMBER(10);
    AVG_SALARY NUMBER(10,2);
BEGIN
    SELECT COUNT(EMPLOYEE_ID), SUM(SALARY), AVG(SALARY)
    INTO TOTAL_EMPLOYEE, TOTAL_SALARY, AVG_SALARY
    FROM EMPLOYEES;
    
    DBMS_OUTPUT.PUT_LINE('총사원의 수: ' || TOTAL_EMPLOYEE);
    DBMS_OUTPUT.PUT_LINE('총급여: ' || TOTAL_SALARY);
    DBMS_OUTPUT.PUT_LINE('평균급여: ' || AVG_SALARY);
END;
/

SELECT COUNT(EMPLOYEE_ID) AS "총사원 수", SUM(SALARY) AS 총급여, ROUND(AVG(SALARY),2) AS 평균급여 FROM EMPLOYEES;


-- 문제 2 Clara 사원의 직무, 급여, 입사일자, 커미션, 부서명을 변수에 대입하여 출력하여 보자.
DECLARE
    VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    VJOB_ID EMPLOYEES.JOB_ID%TYPE;
    VSALARY EMPLOYEES.SALARY%TYPE;
    VHIRE_DATE EMPLOYEES.HIRE_DATE%TYPE;
    VCOMMISSION_PCT EMPLOYEES.COMMISSION_PCT%TYPE;
    VDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE;
    VDEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME, JOB_ID, SALARY, HIRE_DATE, COMMISSION_PCT, E.DEPARTMENT_ID, DEPARTMENT_NAME 
    INTO VFIRST_NAME, VJOB_ID, VSALARY, VHIRE_DATE, VCOMMISSION_PCT, VDEPARTMENT_ID, VDEPARTMENT_NAME
    FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
    WHERE FIRST_NAME = 'Clara';
    
    DBMS_OUTPUT.PUT_LINE('사원명: ' || VFIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('직무: ' || VJOB_ID);
    DBMS_OUTPUT.PUT_LINE('급여: ' || VSALARY);
    DBMS_OUTPUT.PUT_LINE('입사일자: ' || VHIRE_DATE);
    DBMS_OUTPUT.PUT_LINE('커미션: ' || VCOMMISSION_PCT);
    DBMS_OUTPUT.PUT_LINE('부서번호: ' || VDEPARTMENT_ID);
    DBMS_OUTPUT.PUT_LINE('부서명: ' || VDEPARTMENT_NAME);
END;
/

SELECT E.FIRST_NAME, E.JOB_ID, E.SALARY, E.HIRE_DATE, E.COMMISSION_PCT, E.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
WHERE FIRST_NAME = 'Clara';