-- 성적처리테이블
CREATE TABLE GRADES(
    STUNUM NUMBER(4),
    STUNAME VARCHAR2(20) NOT NULL,
    KOR NUMBER(4)NOT NULL,
    ENG NUMBER(4) NOT NULL,
    MATH NUMBER(4) NOT NULL,
    TOTAL NUMBER(4),
    AVG NUMBER(5,1),
    RANK NUMBER(4)
);
ALTER TABLE GRADES ADD CONSTRAINT GRADES_STUNUM_PK PRIMARY KEY(STUNUM);

-- 테이블에 학번, 이름, 국어, 영어, 수학 점수를 입력하면 총점과 평균이 자동 계산되도록 트리거 작성
CREATE OR REPLACE TRIGGER GRADES_TRIGGER
    AFTER INSERT ON GRADES
    FOR EACH ROW
BEGIN
    :NEW.TOTAL := :NEW.KOR + :NEW.ENG + :NEW.MATH;
    :NEW.AVG := :NEW.TOTAL / 3;
END;
/

SELECT * FROM GRADES;
INSERT INTO GRADES VALUES(1,'홍길동',99,80,85);