CREATE SEQUENCE visit_seq  -- 시퀀스이름
   START WITH 1             -- 시작을 1로 설정
   INCREMENT BY 1          -- 증가 값을 1씩 증가
   NOMAXVALUE             -- 최대 값이 무한대
   NOCACHE
   NOCYCLE;

CREATE table VISIT (
    NO       NUMBER(5,0) NOT NULL,
    WRITER   VARCHAR2(20) NOT NULL,
    MEMO     VARCHAR2(4000) NOT NULL,
    REGDATE  DATE NOT NULL
);
ALTER TABLE VISIT ADD CONSTRAINT VISIT_NO_PK PRIMARY KEY(NO);
INSERT INTO VISIT VALUES(VISIT_seq.NEXTVAL, 'KDJ', '처음으로 메모장입력', SYSDATE);
SELECT * FROM VISIT;

CREATE SEQUENCE join_seq  -- 시퀀스이름
   START WITH 1             -- 시작을 1로 설정
   INCREMENT BY 1          -- 증가 값을 1씩 증가
   NOMAXVALUE             -- 최대 값이 무한대
   NOCACHE
   NOCYCLE;

CREATE table JOIN (
    NO        NUMBER(5,0) NOT NULL,
    NAME      VARCHAR2(20) NOT NULL,
    ID        VARCHAR2(30) NOT NULL,
    PW        VARCHAR2(30) NOT NULL,
    PHONE     VARCHAR2(20) NOT NULL,
    BIRTH     VARCHAR2(10) NOT NULL,
    JOINDATE  DATE NOT NULL
);
ALTER TABLE JOIN ADD CONSTRAINT JOIN_NO_PK PRIMARY KEY(NO);
select * from join;
INSERT INTO join VALUES(join_seq.NEXTVAL, '권민성', 'kms12345', 'kms12345', '010-4192-7662', '000918', SYSDATE);